### PR TITLE
Fixed #28, connection timeout doesn't trigger reconnect logic. 

### LINKED ISSUE #28: Initial connect failure fails to trigger reconnect
I have been seeing some odd things when an initial connection times out. It fails to notify that the connection has closed, and thus doesn't trigger the reconnect logic. PR incoming.

### PR DESCRIPTION
**Pull request by i8beef**
Also reworked the connection logic to allow setting up connection callback once, instead of each time connect is called.

### CODE REVIEW

**Comment by i8beef** [comment]
Updated to resolve the conflict with the extra check you added for reconnects.

**Comment by Edubits** [comment]
Thanks again @i8beef! I've just deployed this version to my local Z-Way and will test it over the coming few days. If nothing misbehaves I'll merge it to the master soon and release an update.

**Comment by i8beef** [comment]
Awesome! The refactor on the connection logic separates the connection setup from the connection attempt itself, which should eliminate some moving parts during reconnects. The other change was in the connection logic itself, where a connection TIMEOUT would not signal a connection CLOSE, so it would attempt to reconnect, put the library into "connecting" mode, and then on timeout would be left in that mode, which could leave it in a hung state where the reconnect logic exits early because it thinks a connection is currently in progress already. By calling an explicit disconnect on connection timeout, it clears that lock and when the reconnect runs it goes through as expected. It was tricky to reproduce, but on a connection that might be intermittent for long enough for a reconnect to timeout, you'd see the plugin lose connection and never try and reconnect.

**Comment by i8beef** [comment]
There is still something odd going on here. If the MQTT server goes down for longer than a few seconds, I am still getting failures to reconnect. Don't merge this yet as I'm still testing.

**Pull request merged**
