### PR TITLE
Added feature: Let user decide if duplicate values should be ignored.

### PR DESCRIPTION
**Pull request by Isaksson**
This little fix will make it possible for users to decide if they would like the module to send MQTT message even if the value it self has not changed.

### CODE REVIEW

**Comment by Edubits** [comment]
Good suggestion @Isaksson! I will have to do some changes, as there is a slight overlap with another feature in testing, see PR #19

**Comment by Isaksson** [comment]
Hello. That sounds great.
When the code is merged and working then I have some more changes that I think we need to implement.
I guess you are close to release a new version?

**Comment by Edubits** [comment]
Looking forward to them! 

> I guess you are close to release a new version?

I'm currently testing #24 and as this is quite a big issues for several users I want to release it asap. Plan is to have a beta version available in Zway this weekend and later in the week submit it for release.

**Comment by Isaksson** [comment]
I noticed that PR, that is good changes.
And I think it's good to test and release that code and when that is done maybe start a new branch for the next changes, 1.4 or 1.3.1 depends on how you would like to do the versions.

By the way, great work with this module.

**Comment by Edubits** [comment]
I've just merged the PR after doing some changes to make it compatible with #19. Could you test it in the 1.3 branch? Thanks!

**Comment by Isaksson** [comment]
Good work, I will test and let you know the results.

**Pull request merged**
